apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-api
  template:
    metadata:
      labels:
        app: qr-api
    spec:
      containers:
        - name: qr-api
          image: paularinze/qr-code-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: GCP_BUCKET_NAME
              value: "mrp-qrcode-generator"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcp/GOOGLE_APPLICATION_CREDENTIALS"
          volumeMounts:
            - name: gcp-credentials
              mountPath: /secrets/gcp
              readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
