apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-api
  labels:
    app: qr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-api
  template:
    metadata:
      labels:
        app: qr-api
    spec:
      containers:
      - name: qr-api
        image: paularinze/qr-code-backend:latest # Replace with your image
        ports:
        - containerPort: 80
      #   env:
      #   - name: GOOGLE_APPLICATION_CREDENTIALS
      #     value: /etc/gcp/credentials.json
      #   volumeMounts:
      #   - name: gcp-credentials
      #     mountPath: /etc/gcp
      #     readOnly: true
      # volumes:
      # - name: gcp-credentials
      #   secret:
      #     secretName: gcp-credentials
      #     items:
      #     - key: GOOGLE_APPLICATION_CREDENTIALS
      #       path: credentials.json

        