apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-frontend
  labels:
    app: qr-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-frontend
  template:
    metadata:
      labels:
        app: qr-frontend
    spec:
      containers:
      - name: qr-frontend
        image: paularinze/qr-code-frontend:latest # Replace with your image
        ports:
        - containerPort: 3000
