apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  # namespace: default # Update namespace if needed
type: Opaque
data:
  GOOGLE_APPLICATION_CREDENTIALS: __INSERT_GCP_CREDENTIALS_FILE__BASE64____

