name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]
  # push:
  #   branches:
  #     - main
  #   paths: 
  #     - 'api/Dockerfile'
  #     - 'front-end-nextjs/Dockerfile'
    
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qr-code-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./front-end-nextjs
          push: true
          target: production
          # target: production
          tags: ${{ secrets.DOCKER_USERNAME }}/qr-code-frontend:latest