name: Build and Publish image to Docker Hub
on:
  [workflow_dispatch]
  # push:
  #   branches:
  #     - main
  #   paths: 
  #     - 'api/Dockerfile'
  #     - 'front-end-nextjs/Dockerfile'
    
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push backend image
        run: |
          docker build ./api/ -t paularinze/qr-code-backend:latest
          docker push paularinze/qr-code-backend:latest
      - name:  build and push frontend image
        run: |
          docker build ./front-end-nextjs/ -t paularinze/qr-code-frontend:latest
          docker push paularinze/qr-code-frontend:latest